apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: html
        image: nginx
        command: ["/bin/sh", "-c", "/vagrant/scripts/script_html_app1.sh && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: script
          mountPath: /vagrant/scripts/script_html_app1.sh
      volumes:
      - name: script
        hostPath:
          path: /vagrant/scripts/script_html_app1.sh
          type: File