apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42-playground
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fZpHr/inception-of-things_42/'
    targetRevision: HEAD
    path: 'p3/confs/sync'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true