apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: html
        image: pierrezemb/gostatic
        args: ["-port=80", "-path=/app"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /app
      volumes:
      - name: html
        configMap:
          name: app2-html
          items:
          - key: index.html
            path: index.html